apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-api-config
  namespace: student-app
data:
  SPRING_APPLICATION_NAME: "customer-api"
  SERVER_PORT: "7074"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "false"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info"
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: "never"