{{- if .Values.apiGateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    {{- include "student-app.labels" . | nindent 4 }}
  {{- with .Values.apiGateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.apiGateway.ingress.className }}
  ingressClassName: {{ .Values.apiGateway.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.apiGateway.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.apiGateway.ingress.path | quote }}
            pathType: {{ .Values.apiGateway.ingress.pathType }}
            backend:
              service:
                name: api-gateway
                port:
                  number: {{ .Values.apiGateway.service.port }}
  {{- if .Values.apiGateway.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.apiGateway.ingress.host | quote }}
      secretName: {{ .Values.apiGateway.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
