apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-api-config
  labels:
    app: customer-api
    {{- include "student-app.labels" . | nindent 4 }}
data:
  SPRING_APPLICATION_NAME: {{ .Values.customerApi.config.springApplicationName | quote }}
  SERVER_PORT: {{ .Values.customerApi.config.serverPort | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.customerApi.config.springJpaHibernateDdlAuto | quote }}
  SPRING_JPA_SHOW_SQL: {{ .Values.customerApi.config.springJpaShowSql | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.customerApi.config.managementEndpointsExposureInclude | quote }}
  MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: {{ .Values.customerApi.config.managementEndpointHealthShowDetails | quote }}
