apiVersion: v1
kind: Service
metadata:
  name: customer-api
  labels:
    app: customer-api
    {{- include "student-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.customerApi.service.type }}
  selector:
    app: customer-api
    {{- include "student-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.customerApi.service.port }}
      targetPort: {{ .Values.customerApi.service.targetPort }}
